image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
  - ps: Start-FileDownload 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
build_script:
  - dotnet --version
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: qJri9ljhzPsE+zdwEnGEDYnhF9fK2/ze/Uj40KKT5cYvvnLEd5XL8OrXCdxXL5fN
    skip_symbols: true
    artifact: /.*\.nupkg/  